project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    fontsize: 1.15em
    toc: false
    css: styles.css
    grid:
      body-width: 1100px
      margin-width: 100px
      sidebar-width: 100px


website:
  title: "Pedro Torres"
  navbar:
    background: "#274f63"
    foreground: light
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Other"
        href: other.qmd
  page-footer:
    left: "© 2026 Pedro Javier Torres Lopez"
    right: "p.torres-lopez@lse.ac.uk"

